### ISSUE TITLE
Support for CI 

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/simple-table-component#3]
Build [fails](http://5.79.69.49/job/Clarity%20-%20Simple-table-component/4/console) on CI Server. But I couldn't find out why. 

@DanielRodera Maybe you shouldn't use spaces in project names, maybe that's the problem:
 `Running on Jenkins in /var/jenkins_home/workspace/Clarity - Simple-table-component`

**Comment by DanielRodera** [comment]
Thank you for the report @p-a-s-c-a-l, I have taken a look to the logs and it seems that there is a problem with the yarn install command: 

` _error https://registry.yarnpkg.com/es5-ext/-/es5-ext-0.10.50.tgz: Extracting tar content of undefined failed, the file appears to be corrupt_`

Do you know about this error in yarn??
Where do you get the message you posted??

I will take a look because maybe is related to the file system

**Comment by p-a-s-c-a-l** [comment]
Locally `yarn install` completes without problems.

**Comment by DanielRodera** [comment]
I have made some changes, now seems is working properly.

I also fixed the problem with the "yarn test" command, which runs forever. Below you can see the last test made in Jenkins (triggered by a Github push).

![image](https://user-images.githubusercontent.com/42216407/63767413-dfcb3c00-c8cd-11e9-830c-f8b0c58841a4.png)

Let me know if the problem persists, thanks!

**Comment by p-a-s-c-a-l** [comment]
Yes, of course the problem still persist? Your console screenshot reads: "error Command failed...."

There isn't a single successful build run in [simple-table-component](http://5.79.69.49/job/simple-table-component/).

**Comment by DanielRodera** [comment]
If you take a look to the entire log ([log.txt](https://github.com/clarity-h2020/simple-table-component/files/3546199/log.txt)), there are two modules are missing (CSISRemoteHelpers.test.js and GenericEmikatClient.test.js).

In my opinion, this is why the "error Command failed with exit code 1." message is appearing, could you please take a look to this issue?

Maybe once all these errors are solved the test would pass in the Jenkins pipeline.

**Comment by p-a-s-c-a-l** [comment]
On my local machine and another remote machine, I can build and test the project. Which branch are you using?

**Comment by DanielRodera** [comment]
I am using the 'master' branch.

**Comment by DanielRodera** [comment]
Hi Pascal,

Just to let you know, I have changed the Jenkins´ URL to http://5.79.69.49:78

**Comment by p-a-s-c-a-l** [comment]
@DanielRodera 

503 Service Temporarily Unavailable on port 80 and connection refused on port 78.
Could you please a DNS entry, e.g. ci.clarity-h2020.eu?

**Comment by p-a-s-c-a-l** [comment]
@DanielRodera any news regarding the CI system? http://5.79.69.49:78/ is still not available. As mentioned above, it would be great if you could make it available under http**s**://ci.clarity-h2020.eu.

**Comment by DanielRodera** [comment]
Hi @p-a-s-c-a-l , 

Sorry I didn't see the last post. The CI is working at http://5.79.69.49:78 form the beginning. What problem do you have exactly? I can access Jenkins without a problem, please let me know and I will take a look.

Regarding the DNS, I asked Atos IT people to create the new subdomain in the DNS for our server. Should be ready within today, I will let you know.

**Comment by p-a-s-c-a-l** [comment]
![grafik](https://user-images.githubusercontent.com/1788226/67665841-c8aad800-f96a-11e9-847f-88cc1e29d4b9.png)

403 access denied

**Comment by negroscuro** [comment]
I tried from home and I can access... 

![image](https://user-images.githubusercontent.com/6427900/67668901-1e827e80-f971-11e9-9b63-7f85887cbd96.png)

**Comment by p-a-s-c-a-l** [comment]
Very strange.  [http*s*://ci.clarity-h2020.eu](https://ci.clarity-h2020.eu.) is not reachable and  http://ci.clarity-h2020.eu gives me 

```
503 Service Temporarily Unavailable 
nginx/1.17.3
```

**Comment by DanielRodera** [comment]
Hi @p-a-s-c-a-l,

The http://ci.clarity-h2020.eu/ domain should work properly now. 

The only problem is that the pipeline's configuration has been lost. Could you please add your Github username again in Jenkins?.

The user and password are the same as before.

Thank you!

**Comment by p-a-s-c-a-l** [comment]
All builds fail with 
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[Pipeline] sh
+ docker pull node:latest
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
``` 

See [here](http://ci.clarity-h2020.eu/job/csis-helpers-js/1/console).

@DanielRodera Can you please try to fix this asap? I have to create some screenshot for D4.4. Thanks.

**Comment by p-a-s-c-a-l** [comment]
```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 No valid crumb was included in the request</title>
</head>
<body><h2>HTTP ERROR 403</h2>
<p>Problem accessing /. Reason:
<pre>    No valid crumb was included in the request</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
```

Hooks don't work. Again.

**Comment by p-a-s-c-a-l** [comment]
Enabling proxy compatibility did not work.

![grafik](https://user-images.githubusercontent.com/1788226/68479759-63d96280-0233-11ea-9a24-c13498229412.png)

I know that this problem has happened in the past and I fixed it somehow. But I cannot find the respective issue. Any ideas @DanielRodera ? Turning off CSRF protection is not an option, it's there for a reason. 

BTW, why is the complete Jenkins configuration lost, wasn't there a possibility to export and import it when setting up a new instance?

**Comment by p-a-s-c-a-l** [comment]
Ok, at least the webhooks are working now.

```html
Connection: keep-alive
Content-Length: 2
Date: Fri, 08 Nov 2019 13:33:33 GMT
Server: nginx/1.9.9
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
```

Probably it took some time for the [settings](https://user-images.githubusercontent.com/1788226/68479759-63d96280-0233-11ea-9a24-c13498229412.png) to take effect. Now just [this problem](https://github.com/clarity-h2020/simple-table-component/issues/3#issuecomment-551575169) has to be resolved.

**Comment by DanielRodera** [comment]
> BTW, why is the complete Jenkins configuration lost, wasn't there a possibility to export and import it when setting up a new instance?

I deleted the Jenkins settings by mistake when I was trying to configure the proxy. A backup script should be configured in our server but it wasn't due to a maintenance task done before. Now we have the backup script working properly.

> I know that this problem has happened in the past and I fixed it somehow. But I cannot find the respective issue. Any ideas @DanielRodera ? Turning off CSRF protection is not an option, it's there for a reason.

The Jenkins is already proxied in our server and its working properly. Do you need a specific action for me regarding this??

Last, I cannot see your credentials stored in the Jenkins yet. Would be nice to have then to make tests. Could you please add??

**Comment by p-a-s-c-a-l** [comment]
>  I cannot see your credentials stored in the Jenkins yet.

Pull access is allowed for all. I don't understand why this is needed. For sure I won't upload my private key there. 

Anyway, instead I've created and added a separate [deploy key](https://github.com/clarity-h2020/simple-table-component/settings/keys) some time ago, but ATM I don't have time to reconfigure this again in Jenkins.

**Comment by DanielRodera** [comment]
Everything is working now. 

The "map-component" repository hasn't passed the test but this is related with the yarn, not the Jenkins configuration.

> Pull access is allowed for all. I don't understand why this is needed. For sure I won't upload my private key there.

> Anyway, instead I've created and added a separate deploy key some time ago, but ATM I don't have time to reconfigure this again in Jenkins.

Yes, I was referring to a deploy key. If the pull access is allowed for all, is more than enough for the moment. No problem for my side.

Thank you very much @p-a-s-c-a-l !!!

**Comment by p-a-s-c-a-l** [comment]
Last build failed with: Bind for 0.0.0.0:3010 failed: port is already allocated.
Seems we have to disable disable concurrent builds.

```java
java.io.IOException: Failed to run image 'node:latest'. Error: docker: Error response from daemon: driver failed programming external connectivity on endpoint gifted_joliot (aca34188da361f0a7fbc848ee33df68f571c6631235a2441fed0b81e46540502): Bind for 0.0.0.0:3010 failed: port is already allocated.
	at org.jenkinsci.plugins.docker.workflow.client.DockerClient.run(DockerClient.java:133)
	at org.jenkinsci.plugins.docker.workflow.WithContainerStep$Execution.start(WithContainerStep.java:186)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at org.jenkinsci.plugins.docker.workflow.Docker$Image.inside(Docker.groovy:120)
	at org.jenkinsci.plugins.docker.workflow.Docker.node(Docker.groovy:66)
	at org.jenkinsci.plugins.docker.workflow.Docker$Image.inside(Docker.groovy:108)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.impl.DockerPipelineScript.runImage(DockerPipelineScript.groovy:54)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.impl.AbstractDockerPipelineScript.configureRegistry(AbstractDockerPipelineScript.groovy:73)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.impl.AbstractDockerPipelineScript.run(AbstractDockerPipelineScript.groovy:52)
	at org.jenkinsci.plugins.pipeline.modeldefinition.agent.CheckoutScript.checkoutAndRun(CheckoutScript.groovy:61)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:84)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by p-a-s-c-a-l** [comment]
done
